using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace Archspace2
{
    public class UniverseSettings
    {
        public UniverseSettings()
        {
            BotNames = new List<string>();
            ClusterNames = new List<string>();
        }

        [JsonProperty("StartingBotCount")]
        public int StartingBotCount { get; set; }
        [JsonProperty("StartingClusterCount")]
        public int StartingClusterCount { get; set; }
        [JsonProperty("StartingCouncilCount")]
        public int StartingCouncilCount { get; set; }

        [JsonProperty("BotNames")]
        public List<string> BotNames { get; set; }
        [JsonProperty("ClusterNames")]
        public List<string> ClusterNames { get; set; }

        public static UniverseSettings CreateDefault()
        {
            UniverseSettings result = new UniverseSettings();

            result.StartingBotCount = 20;
            result.StartingClusterCount = 7;
            result.StartingCouncilCount = 3;

            result.BotNames = new List<string>()
            {
                "Cypherus",
                "DarkTempes",
                "Penzdragon",
                "Maxtor",
                "Nightshade",
                "Redjack",
                "Torque",
                "BadCBX",
                "Smartguy",
                "Ethereals",
                "Seiffer",
                "Xenoage",
                "Gaia",
                "Nemesis",
                "HippieHunter",
                "Soundwave",
                "BoneyMan",
                "DarkArchon",
                "nefus",
                "Oxygen",
                "Liquid",
                "devious",
                "Locke",
                "Avrem",
                "Azrael",
                "MadPrig",
                "Neo",
                "WarPig",
                "CLown",
                "Rage",
                "JenniferLee",
                "hxc",
                "Hyun",
                "Azreth",
                "Exxtractor",
                "phat",
                "Gueust",
                "lalala",
                "DOCTORWHO",
                "stlhd",
                "Chaoslord",
                "ChaosAngel",
                "Gumpus",
                "Redeemer",
                "Trotsky",
                "NiftyNiftarious",
                "Reaper",
                "Merc",
                "Wolverine",
                "Trotsky",
                "Khyber",
                "hawk",
                "Knight",
                "MadKat",
                "Azdgari",
                "Houston",
                "Blaze",
                "Kenshin",
                "Grady",
                "Xinhal",
                "Keyan",
                "Kelly",
                "zbyte",
                "Mindwarper",
                "Leena",
                "Kiria",
                "ShadowmanZERO",
                "Infestor",
                "UnDos",
                "LordManiac",
                "Jinn",
                "Replicator",
                "destroyer",
                "Wintermute",
                "Vish",
                "DCXero",
                "DrJekyl",
                "Palin",
                "Trigon",
                "Samite",
                "Targon",
                "Witchblade",
                "WarlorD",
                "Moonwitch",
                "Occultus",
                "goodie",
                "Windpast",
                "Rain",
                "Tara",
                "Shadowfire",
                "darkfyre",
                "Talamioros",
                "Vector3",
                "XenoTerror",
                "LeetMasterAce",
                "Jessica",
                "riogilao",
                "LordZolan",
                "IceCool",
                "GIJoe",
                "lurker",
                "Rosengaard",
                "ElGobblo",
                "Deacon",
                "opus",
                "dragush",
                "nitrogen",
                "Frostys",
                "stanleyipcuss",
                "Elodea",
                "Noldor",
                "DaveMcW",
                "HokkusPokkus",
                "Dream",
                "lildragon",
                "darlie",
                "Jusron",
                "KatarHol",
                "Banchee",
                "steelgut",
                "Aaron",
                "Nana",
                "Jadore",
                "Charlie",
                "Invincible",
                "Rino-TT",
                "RedSky",
                "Charisma",
                "DumDum",
                "RedEye",
                "laserstorm",
                "Clyde",
                "EvilDrac",
                "Trekkie197",
                "Duran"
            };
            result.ClusterNames = new List<string>()
            {
                "Aditi"
                ,"Aglaia"
                ,"Agni"
                ,"Akongo"
                ,"Alako"
                ,"Allekto"
                ,"Amentet"
                ,"Ammon"
                ,"Amphitrite"
                ,"Anuket"
                ,"Aphrodite"
                ,"Aplu"
                ,"Arebati"
                ,"Arma"
                ,"Arsu"
                ,"Asnan"
                ,"Asteria"
                ,"Atargatis"
                ,"Atlaua"
                ,"Atropos"
                ,"Atum"
                ,"Baal"
                ,"Bacab"
                ,"Bagvarti"
                ,"Baldur"
                ,"Behedti"
                ,"Bel"
                ,"Bellona"
                ,"Bhagwan"
                ,"Boreas"
                ,"Bragi"
                ,"Brahma"
                ,"Bress"
                ,"Brigantia"
                ,"Britomartis"
                ,"Buluga"
                ,"Candra"
                ,"Cath"
                ,"Ceres"
                ,"Chac"
                ,"Cheiron"
                ,"Cihuacoatl"
                ,"Cinteotl"
                ,"Cinvat"
                ,"Concordia"
                ,"Curche"
                ,"Dabog"
                ,"Dagda"
                ,"Dedun"
                ,"Dievs"
                ,"Diomedes"
                ,"Djata"
                ,"Dolichenus"
                ,"Durga"
                ,"Dyaus"
                ,"Ea"
                ,"Egres"
                ,"Ekchuah"
                ,"Elkunirsa"
                ,"Epona"
                ,"Erato"
                ,"Esus"
                ,"Eule"
                ,"Euphrosine"
                ,"Euros"
                ,"Euterpe"
                ,"Faro"
                ,"Fjorgyn"
                ,"Flora"
                ,"Forseti"
                ,"Fortuna"
                ,"Freyja"
                ,"Frigg"
                ,"Gaia"
                ,"Gemini"
                ,"Govannon"
                ,"Gwydyon"
                ,"Haldi"
                ,"Hazzi"
                ,"Hekate"
                ,"Hel"
                ,"Hephaistos"
                ,"Hermaphroditos"
                ,"Hermes"
                ,"Heruka"
                ,"Hestia"
                ,"Hezur"
                ,"Hinkon"
                ,"Hoedr"
                ,"Horai"
                ,"Horus"
                ,"Huan"
                ,"Hubal"
                ,"Huracan"
                ,"Idun"
                ,"Illapa"
                ,"Indra"
                ,"Inmar"
                ,"Inuus"
                ,"Isara"
                ,"Isis"
                ,"Ishtar"
                ,"Jabru"
                ,"Jamm"
                ,"Jarri"
                ,"Jord"
                ,"Juno"
                ,"Juventas"
                ,"Jyotishka"
                ,"Kali"
                ,"Kama"
                ,"Karta"
                ,"Kataragama"
                ,"Klotho"
                ,"Korrawi"
                ,"Kotar"
                ,"Kubera"
                ,"Kukulcan"
                ,"Kusuh"
                ,"Lachesis"
                ,"Laima"
                ,"Lakshmi"
                ,"Laran"
                ,"Larunda"
                ,"Laverna"
                ,"Libera"
                ,"Lodur"
                ,"Loki"
                ,"Lucina"
                ,"Luna"
                ,"Mah"
                ,"Maia"
                ,"Maitreya"
                ,"Malakbel"
                ,"Manannan"
                ,"Marduk"
                ,"Marici"
                ,"Maui"
                ,"Megaira"
                ,"Meness"
                ,"Menhit"
                ,"Menulis"
                ,"Metis"
                ,"Midir"
                ,"Minerva"
                ,"Mitra"
                ,"Morgoth"
                ,"Moloch"
                ,"Mugasa"
                ,"Musisi"
                ,"Nahhundi"
                ,"Nammu"
                ,"Napir"
                ,"Narisah"
                ,"Nechbet"
                ,"Nemesis"
                ,"Nephthys"
                ,"Nereus"
                ,"Nergal"
                ,"Nerthus"
                ,"Nirah"
                ,"Nirrti"
                ,"Nisaba"
                ,"Njord"
                ,"Nortia"
                ,"Notos"
                ,"Nun"
                ,"Nusku"
                ,"Nzambi"
                ,"Odin"
                ,"Ogmios"
                ,"Okeanos"
                ,"Olokun"
                ,"Orcus"
                ,"Orion"
                ,"Orpheus"
                ,"Osiris"
                ,"Oya"
                ,"Pachet"
                ,"Pariacaca"
                ,"Parjanya"
                ,"Peitho"
                ,"Pemba"
                ,"Perkons"
                ,"Persaios"
                ,"Pleiades"
                ,"Pomona"
                ,"Pon"
                ,"Prende"
                ,"Priapos"
                ,"Ptah"
                ,"Pudicitia"
                ,"Pushan"
                ,"Ordal"
                ,"Qaynyan"
                ,"Quat"
                ,"Quilla"
                ,"Quzah"
                ,"Rat-taui"
                ,"Raudna"
                ,"Renenutet"
                ,"Reshef"
                ,"Rind"
                ,"Rongo"
                ,"Rosmerta"
                ,"Rudra"
                ,"Sachmet"
                ,"Sadrapa"
                ,"Samvara"
                ,"Sarasvati"
                ,"Sedna"
                ,"Sentait"
                ,"Sequana"
                ,"Serket-hetu"
                ,"Seth"
                ,"Sethlans"
                ,"Shosshu"
                ,"Shurdi"
                ,"Sif"
                ,"Silvanus"
                ,"Singbonga"
                ,"Sirona"
                ,"Sitala"
                ,"Siva"
                ,"Skanda"
                ,"Skuld"
                ,"Sokar"
                ,"Sol"
                ,"Soma"
                ,"Sopdu"
                ,"Sucellos"
                ,"Sulmanu"
                ,"Summamus"
                ,"Surya"
                ,"Svarog"
                ,"Tabiti"
                ,"Tailtiu"
                ,"Tapio"
                ,"Tangaroa"
                ,"Taranis"
                ,"Tate"
                ,"Teisiphone"
                ,"Tellus"
                ,"Thaleia"
                ,"Thanatos"
                ,"Thesan"
                ,"Themis"
                ,"Thor"
                ,"Turan"
                ,"Tyche"
                ,"Ugar"
                ,"Ukko"
                ,"Ullr"
                ,"Unut"
                ,"Upulvan"
                ,"Urd"
                ,"Ushas"
                ,"Utu"
                ,"Vali"
                ,"Varda"
                ,"Varunya"
                ,"Vata"
                ,"Vayu"
                ,"Veive"
                ,"Verdandi"
                ,"Vesta"
                ,"Virtus"
                ,"Vishnu"
                ,"Voer"
                ,"Volumna"
                ,"Votan"
                ,"Vritra"
                ,"Vulcanus"
                ,"Wadd"
                ,"Whiro"
                ,"Wunekau"
                ,"Wurunkatte"
                ,"Xochipilli"
                ,"Xocotl"
                ,"Yama"
                ,"Yarhibol"
                ,"Yavanna"
                ,"Yehl"
                ,"Zalmoxis"
                ,"Zemyna"
                ,"Zephyros"
                ,"Zeus"
            };

            return result;
        }
    }
}
